import {
  Tag,
  ShoppingCart,
  Briefcase,
  Wallet,
  TrendingUp,
  PlusCircle,
  Users,
  Building2,
  Zap,
  Landmark,
  Package,
  Truck,
  Megaphone,
  Monitor,
  Sparkles,
  Shield,
  GraduationCap,
  CreditCard,
  MoreHorizontal,
  Home,
  Heart,
  Book,
  Car,
  Film,
  Utensils,
  Laptop,
  DollarSign,
  Banknote,
  Receipt,
  Store,
  Wrench,
  Lightbulb,
  Globe,
  Phone,
  Smartphone,
  Flame,
  Droplets,
  Tv,
  Wifi,
  Lock,
  FileText,
  Printer,
  Coffee,
  Plane,
  Gift,
  ShoppingBag,
  Scissors,
  Hammer,
  Settings,
  BarChart3,
  PieChart,
  Target,
  Award,
  Star,
  Bell,
  Calendar,
  Clock,
  Map,
  MapPin,
  Navigation,
  Fuel,
  CircleDollarSign,
  BadgeDollarSign,
  Scale,
  Gavel,
  Stethoscope,
  Pill,
  Dumbbell,
  Music,
  Gamepad2,
  Palette,
  Camera,
  Video,
  Headphones,
  Radio,
  Newspaper,
  BookOpen,
  PenTool,
  Code,
  Server,
  Database,
  Cloud,
  HardDrive,
  Cpu,
  Boxes,
  Container,
  Factory,
  Warehouse,
  TreePine,
  Leaf,
  Recycle,
  ShieldCheck,
  BadgeCheck,
  UserCheck,
  UserPlus,
  ClipboardList,
  FileSpreadsheet,
  Calculator,
  Percent,
  TrendingDown,
  ArrowUpRight,
  ArrowDownRight,
} from 'lucide-react';

const ICON_MAP = {
  'tag': Tag,
  'shopping-cart': ShoppingCart,
  'briefcase': Briefcase,
  'wallet': Wallet,
  'trending-up': TrendingUp,
  'plus-circle': PlusCircle,
  'users': Users,
  'building-2': Building2,
  'zap': Zap,
  'landmark': Landmark,
  'package': Package,
  'truck': Truck,
  'megaphone': Megaphone,
  'monitor': Monitor,
  'sparkles': Sparkles,
  'shield': Shield,
  'graduation-cap': GraduationCap,
  'credit-card': CreditCard,
  'more-horizontal': MoreHorizontal,
  'home': Home,
  'heart': Heart,
  'book': Book,
  'car': Car,
  'film': Film,
  'utensils': Utensils,
  'laptop': Laptop,
  'dollar-sign': DollarSign,
  'banknote': Banknote,
  'receipt': Receipt,
  'store': Store,
  'wrench': Wrench,
  'lightbulb': Lightbulb,
  'globe': Globe,
  'phone': Phone,
  'smartphone': Smartphone,
  'flame': Flame,
  'droplets': Droplets,
  'tv': Tv,
  'wifi': Wifi,
  'lock': Lock,
  'file-text': FileText,
  'printer': Printer,
  'coffee': Coffee,
  'plane': Plane,
  'gift': Gift,
  'shopping-bag': ShoppingBag,
  'scissors': Scissors,
  'hammer': Hammer,
  'settings': Settings,
  'bar-chart-3': BarChart3,
  'pie-chart': PieChart,
  'target': Target,
  'award': Award,
  'star': Star,
  'bell': Bell,
  'calendar': Calendar,
  'clock': Clock,
  'map': Map,
  'map-pin': MapPin,
  'navigation': Navigation,
  'fuel': Fuel,
  'circle-dollar-sign': CircleDollarSign,
  'hand-coins': Banknote,
  'badge-dollar-sign': BadgeDollarSign,
  'scale': Scale,
  'gavel': Gavel,
  'stethoscope': Stethoscope,
  'pill': Pill,
  'dumbbell': Dumbbell,
  'music': Music,
  'gamepad-2': Gamepad2,
  'palette': Palette,
  'camera': Camera,
  'video': Video,
  'headphones': Headphones,
  'radio': Radio,
  'newspaper': Newspaper,
  'book-open': BookOpen,
  'pen-tool': PenTool,
  'code': Code,
  'server': Server,
  'database': Database,
  'cloud': Cloud,
  'hard-drive': HardDrive,
  'cpu': Cpu,
  'boxes': Boxes,
  'container': Container,
  'factory': Factory,
  'warehouse': Warehouse,
  'tree-pine': TreePine,
  'leaf': Leaf,
  'recycle': Recycle,
  'shield-check': ShieldCheck,
  'badge-check': BadgeCheck,
  'user-check': UserCheck,
  'user-plus': UserPlus,
  'clipboard-list': ClipboardList,
  'file-spreadsheet': FileSpreadsheet,
  'calculator': Calculator,
  'percent': Percent,
  'trending-down': TrendingDown,
  'arrow-up-right': ArrowUpRight,
  'arrow-down-right': ArrowDownRight,
};

export function getCategoryIcon(iconName) {
  return ICON_MAP[iconName] || Tag;
}

// Grouped icon options for the icon picker UI
export const ICON_GROUPS = [
  {
    label: 'Finanzas',
    icons: [
      'dollar-sign', 'banknote', 'credit-card', 'wallet', 'receipt',
      'circle-dollar-sign', 'hand-coins', 'badge-dollar-sign',
      'trending-up', 'trending-down', 'bar-chart-3', 'pie-chart',
      'calculator', 'percent', 'landmark',
    ],
  },
  {
    label: 'Negocio',
    icons: [
      'briefcase', 'building-2', 'store', 'factory', 'warehouse',
      'shopping-cart', 'shopping-bag', 'package', 'boxes', 'container',
      'users', 'user-check', 'user-plus', 'clipboard-list', 'file-spreadsheet',
    ],
  },
  {
    label: 'Servicios',
    icons: [
      'zap', 'droplets', 'flame', 'wifi', 'globe',
      'phone', 'smartphone', 'tv', 'radio',
      'shield', 'shield-check', 'lock',
    ],
  },
  {
    label: 'Transporte',
    icons: [
      'car', 'truck', 'fuel', 'plane', 'navigation',
      'map', 'map-pin',
    ],
  },
  {
    label: 'Tecnología',
    icons: [
      'monitor', 'laptop', 'cpu', 'server', 'database',
      'cloud', 'hard-drive', 'code', 'settings',
    ],
  },
  {
    label: 'Oficina y Hogar',
    icons: [
      'home', 'printer', 'file-text', 'pen-tool', 'newspaper',
      'sparkles', 'wrench', 'hammer', 'scissors',
      'coffee', 'lightbulb', 'bell',
    ],
  },
  {
    label: 'Educación y Legal',
    icons: [
      'graduation-cap', 'book', 'book-open', 'award', 'star',
      'scale', 'gavel', 'badge-check',
    ],
  },
  {
    label: 'Salud y Ocio',
    icons: [
      'heart', 'stethoscope', 'pill', 'dumbbell',
      'film', 'music', 'gamepad-2', 'camera', 'video',
      'headphones', 'palette', 'gift',
    ],
  },
  {
    label: 'Naturaleza',
    icons: [
      'tree-pine', 'leaf', 'recycle',
    ],
  },
  {
    label: 'Otros',
    icons: [
      'tag', 'target', 'calendar', 'clock',
      'megaphone', 'utensils', 'plus-circle', 'more-horizontal',
      'arrow-up-right', 'arrow-down-right',
    ],
  },
];

export const ALL_ICON_NAMES = Object.keys(ICON_MAP);

export default ICON_MAP;
